.TH PRIME "1" "June 2026" "prime v1.0.1" "User Commands"
.SH NAME
prime \- check for prime numbers
.SH SYNOPSIS
.SY
.B prime
[\fI\,OPTION\/\fR]... [\fI\,NUM\/\fR]...
.YS
.SH DESCRIPTION
.B prime
checks numbers for primality; that is, it checks if \fINUM\fR is prime.
If \fINUM\fR is prime, it outputs 'prime', else 'composite.'
.PP
Note that the test used is probabalistic.
That is, a number which is reported to be composite is definitely composite, but a number reported prime may be composite.
At present, no known counterexamples exist for the test used, having been checked directly to 2^64.
It is, however, expected that infinitely many counterexamples may exist.
A secondary test is also optionally performed; this test uses a series of repetitions with different bases to provide more reason to be confident a number is indeed prime.
The \fB-r\fR flag controls the number of repetitions used.
.PP
To be specific, the GNU MP `\fBmpz_probab_prime_p()\fR` function is used to check for probable primality.
It first does trial division by small factors, and then performs the Baillie-PSW Probable Primality Test.
Afterwards, it does Miller-Rabin probabalistic primality tests.
.PP
Output is given as 'NUM: isprime(NUM)\\n'.
.PP
If no \fINUM\fRs are specified on the command line, read them from standard input.
.SH OPTIONS
Mandatory options to long options are mandatory for short options too.
.TP
.TP
\fB\-l\fR, \fB\-\-loose\-exit\fR
Change the behavior of the exit status.
Normally, the program will exit non-zero if any invalid input is provided.
This flag will change the behavior such that the program will only exit non-zero if a fatal error is encountered.
.TP
\fB\-r\fR, \fB\-\-repetitions\fR=\fI\,REPS\/\fR
Perform \fIREPS\fR repetitions of Miller-Rabin probabalistic primality tests.
Reasonable values are on the order of 15-50, though for numbers less than 2^64 (18446744073709551616), none may be used.
The asymptotic probability of a composite number passing this test is 1/(4^\fIREPS\fR).
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Disable the printing of \fINUM\fR with the computed number.
This is probably more useful for scripts, but really probably is never going to be used.
.TP
\fB\-s\fR, \fB\-\-silent\fR
Supress all error messages.
.TP
\fB\-h\fR, \fB\-\-help\fR
Print a short help message and exit.
.TP
\fB\-v\fR, \fB\-\-version\fR
Print version information and exit.
.PP
.SH AUTHOR
Written by Jack R. Uteg.
.SH COPYRIGHT
Copyright \(co 2026 Jack Renton Uteg.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH SEE ALSO
.TP
\fBbaseconv(1)\fR, \fBcollatz(1)\fR, \fBfib(1)\fR, \fBfactor(1)\fR, \fBpoly(1)\fR
